dist: trusty
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .[test]
  - python setup.py sdist bdist_wheel
script:
  - py.test
deploy:
  - provider: releases
    api_key:
      secure: EzaYFdg3fDapTW1jkM3ITU/BjcXJU71reuhUt3HzUglJzWH5/JGayjv77P+uku6SYcSNOl8IRzxAmreqlpsPUp8kYNbA995qKaw2taQQ0HcR39D3etiaVdFhS7AHIjPGMfNNtL+8YFMuBnRYG6R2OItoVtdFJ+BbFMbqxR23uNF1JcGnYURvP79GQoGr8xb+UgNPAWdJN0/XjYefIkRou42Rb0Lq97OIkSY34RofDMGLvjYjB8mhfIT/EIUiutdIovm9l9t6PxN0ULOilfi9QuMuRJZsGCKGMwTJ2Hg9gaZA0gCR0Q/KO1yhwpGe/OD9JofATPWKy17jRNy83vjQeAWb1banx4NtN7xZvNlWQD5imU/X3Rz79gxpEpFOBWFvpjlASViUxFncORGD6MgQr4jau2InIQguwy1arTaNcNfEWtYRACX8UQII8Pgz6kwhlKkfThEcVnzq7h+W636oujZL5DXASHdigiEkfXGNuIjOyT2cedfipk6BCtiIpBwdWKz6LWx/Whq/kW1TLhYtz7grk/MvGTyA9mdyf32j5uHxupu/FtEeMSoH+zclcO2U0I8EhMy5DjyiBhK1f0IhAcyC8ws+ckRAaBktCq2LsyXYIhDFji4cBR5ODkW/NRvpRmRlWlx6IMf+Uxe66zjilG4/sVmNZBOJI+ynJ2t21S4=
    file_glob: true
    file:
      - dist/hetio-*.tar.gz
      - dist/hetio-*.whl
    on:
      python: '3.6'
      repo: dhimmel/hetio
      tags: true
  - provider: pypi
    user: dhimmel
    password:
      secure: DG8uk3jcTfy6veFO7G0EpSK6KzCsCJV05dyOj/gixuZ6POJLEfOeDO97AIO1JMwZCcSfEoHQrY/udOqmh45sMShEW/CICDo4a+BkQl/7XbnNa7sul7Gz16HugkRdAG2SmqGY8ZTUnawdfn6HAnSojhduZ1xKpoxQNXwfExt/YOHKaj4c9jdknmX4m+Y6FitciA/l3Bbd98VpAvIs8rdJvSQHVKSHLXKwKLjJUF+LeWaL663sxmKJo1LcH99b805UIbf8eIpPTcY2j/sZTIavrbhSpllF864GS260yLWdSsjP/yhGtmiHrPKdlFInwoVlPMMmbrQkkocSmgLnnOe9lXekOrb7bRbE/BB3n6Q1GQWoBROLkMuQW+uP3AU9pAx9Md4b7BSkvsvRANaJrASXGxqJT5fYGjWIj4A43Giq6nhzH2wVfBpC9Qovp12mrZ0O8AS8np0FYmyJhFxc1upfA5js8UbEeHq6Kf46ka6pWaWUZG/nRr2cEXGvekbNDeXhirzNYCl+h/SLpva9iCHW3KBc+9qUKujueba63kty0j4UsS6Tfqw12r5/WNfPbQ0OxFNBBQRpFN08jmQ2kFTbFEscLgPlaxezuZ4JVOqDenWElG+no2mdiTB+o27DJHxQQnrL9XTKJgDNYSohzW19dPOtBq5bJT5L7J2ZehqMNj8=
    on:
      python: '3.6'
      repo: dhimmel/hetio
      tags: true
      distributions: sdist bdist_wheel
      branch: deploy
